swagger_ui:
  version: VERSION
  css:
    theme:
      /libraries/swagger_ui/dist/swagger-ui.css: { minified: true }
  js:
    /libraries/swagger_ui/dist/swagger-ui-bundle.js: { minified: true }
    /libraries/swagger_ui/dist/swagger-ui-standalone-preset.js: { minified: true }
    js/swagger_ui_formatter.js: {}
  dependencies:
    - core/jquery
    - core/drupalSettings
